import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import StyledComponentsRegistry from "@/app/lib/registry";
import React from "react";
import Header from "@/components/header/header";
import RouteTransition from "@/components/routeTransition/routeTransition";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
          <Header/>
          <RouteTransition>{children}</RouteTransition>
      </>
  );
}
