import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import StyledComponentsRegistry from "@/app/lib/registry";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className} style={{ backgroundColor: "#3a77ff" }}>
        <StyledComponentsRegistry>
            <main>{children}</main>
        </StyledComponentsRegistry>
        </body>
        </html>
    );
}